"""Synthetic phase-2 catalog with realistic near-neighbor tools."""

CATALOG_120: dict[str, str] = {
    # files
    "files_read_document": "Read the full contents of a known document path.",
    "files_write_document": "Create or replace a document at a specified path.",
    "files_append_document": "Append supplied text to the end of a document.",
    "files_copy_document": "Copy one document to a new path without changing the source.",
    "files_move_document": "Move a document to a new path and remove the old entry.",
    "files_delete_document": "Delete a specified document from the file store.",
    "files_list_directory": "List files and folders directly inside a directory.",
    "files_search_content": "Search document contents for a text or regular expression.",
    "files_find_path": "Find paths whose file names match a supplied pattern.",
    "files_compare_documents": "Compare two document versions and return their changed lines.",
    "files_get_metadata": "Return size, timestamps, type, and checksum for a path.",
    "files_set_permissions": "Set read, write, and execute permissions on a path.",
    # shell
    "shell_run_command": "Run one shell command and return its exit status and output.",
    "shell_start_process": "Start a shell process that continues after the request ends.",
    "shell_stop_process": "Ask a running process to stop gracefully by process id.",
    "shell_restart_process": "Stop and start a named process using its saved command.",
    "shell_stream_output": "Stream live stdout and stderr from a running process.",
    "shell_capture_output": "Run a command and collect all stdout and stderr before returning.",
    "shell_set_environment": "Set an environment variable for later shell commands.",
    "shell_get_environment": "Read the current value of one shell environment variable.",
    "shell_list_processes": "List running processes with ids, commands, and owners.",
    "shell_kill_process": "Forcefully terminate a process by its process id.",
    "shell_run_script": "Execute a local script file with the supplied arguments.",
    "shell_check_exit": "Check the recorded exit status of a completed process.",
    # web
    "web_search_pages": "Search indexed web pages for a query and return ranked results.",
    "web_fetch_page": "Fetch a known web page URL and return its readable content.",
    "web_fetch_file": "Fetch a known URL and return its file bytes.",
    "web_open_link": "Open a link from a page and return the destination page.",
    "web_extract_text": "Extract visible text from a fetched web page.",
    "web_extract_links": "Extract destination URLs from links on a fetched page.",
    "web_check_status": "Check the current HTTP status for one URL.",
    "web_monitor_status": "Poll a URL and report changes in its HTTP status.",
    "web_submit_form": "Submit fields to a web form at a specified URL.",
    "web_download_asset": "Download a named asset from a web page to local storage.",
    "web_upload_asset": "Upload a local asset to an endpoint that accepts files.",
    "web_validate_url": "Validate URL syntax and resolve its host name.",
    # calendar
    "calendar_create_event": "Create a calendar event with time, title, and attendees.",
    "calendar_update_event": "Change fields on an existing calendar event.",
    "calendar_cancel_event": "Cancel an existing event and notify its attendees.",
    "calendar_move_event": "Move an event to a different date or time zone.",
    "calendar_list_events": "List calendar events within a supplied time range.",
    "calendar_find_events": "Find calendar events matching a title or attendee.",
    "calendar_get_availability": "Return free and busy intervals for selected calendars.",
    "calendar_book_slot": "Book an open time slot and create its calendar event.",
    "calendar_add_attendee": "Add one attendee to an existing calendar event.",
    "calendar_remove_attendee": "Remove one attendee from an existing calendar event.",
    "calendar_create_reminder": "Create a reminder scheduled before a specified time.",
    "calendar_snooze_reminder": "Delay an existing reminder until a later time.",
    # email
    "email_send_message": "Send a new email message to specified recipients.",
    "email_draft_message": "Save a new email message without sending it.",
    "email_reply_thread": "Send a reply in an existing email conversation.",
    "email_forward_message": "Forward an existing email to new recipients.",
    "email_archive_message": "Remove an email from the inbox without deleting it.",
    "email_delete_message": "Move an email or thread to the trash.",
    "email_search_messages": "Search email bodies and subjects for a query.",
    "email_find_thread": "Find the conversation containing a known message id.",
    "email_mark_read": "Mark selected email messages as read.",
    "email_mark_unread": "Mark selected email messages as unread.",
    "email_add_label": "Apply a label to selected email messages.",
    "email_remove_label": "Remove a label from selected email messages.",
    # crm
    "crm_create_contact": "Create a CRM contact with identity and company fields.",
    "crm_update_contact": "Update fields on an existing CRM contact.",
    "crm_merge_contacts": "Merge two duplicate contacts and keep one record.",
    "crm_create_company": "Create a CRM company with its account details.",
    "crm_update_company": "Update fields on an existing CRM company.",
    "crm_log_activity": "Record a call, meeting, or task against a CRM record.",
    "crm_add_note": "Add a free-text note to a CRM contact or company.",
    "crm_search_contacts": "Search contacts by name, email, or company.",
    "crm_find_deal": "Find a deal by name, account, or external identifier.",
    "crm_create_deal": "Create a deal with value, stage, and account fields.",
    "crm_update_deal": "Change fields on an existing CRM deal.",
    "crm_close_deal": "Close a deal as won or lost with a final reason.",
    # deploy
    "deploy_build_artifact": "Build a versioned deploy artifact from source.",
    "deploy_start_release": "Start a release to the configured deployment target.",
    "deploy_promote_release": "Promote a tested release to the next environment.",
    "deploy_rollback_release": "Restore the last healthy release in an environment.",
    "deploy_pause_rollout": "Pause an in-progress rollout without changing its version.",
    "deploy_resume_rollout": "Resume a paused rollout from its current position.",
    "deploy_scale_service": "Change the instance count for a deployed service.",
    "deploy_restart_service": "Restart all instances of a deployed service.",
    "deploy_view_logs": "Read recent application logs from a deployed service.",
    "deploy_check_health": "Check health probes and readiness for a deployed service.",
    "deploy_create_environment": "Create an isolated deployment environment with settings.",
    "deploy_delete_environment": "Delete an empty deployment environment and its settings.",
    # data
    "data_query_table": "Run a read-only query against a named table.",
    "data_insert_rows": "Insert new rows into a named table.",
    "data_update_rows": "Update matching rows in a named table.",
    "data_delete_rows": "Delete matching rows from a named table.",
    "data_export_csv": "Export selected table rows as a CSV file.",
    "data_import_csv": "Load rows from a CSV file into a named table.",
    "data_create_table": "Create a table with the supplied column schema.",
    "data_drop_table": "Permanently remove a table and its stored rows.",
    "data_describe_table": "Return columns, types, keys, and indexes for a table.",
    "data_count_rows": "Count rows matching a filter in a named table.",
    "data_validate_schema": "Check imported data against a table schema.",
    "data_compare_snapshots": "Compare two table snapshots and list row differences.",
    # chat
    "chat_send_message": "Send a new message to a chat channel or direct chat.",
    "chat_edit_message": "Change the text of an existing chat message.",
    "chat_delete_message": "Delete an existing chat message from its conversation.",
    "chat_reply_thread": "Reply to an existing threaded chat message.",
    "chat_start_thread": "Start a new thread from a chat message.",
    "chat_close_thread": "Close an open chat thread and prevent new replies.",
    "chat_search_messages": "Search chat message text across selected conversations.",
    "chat_get_history": "Return messages from a chat conversation and time range.",
    "chat_add_reaction": "Add an emoji reaction to a chat message.",
    "chat_remove_reaction": "Remove your reaction from a chat message.",
    "chat_upload_file": "Upload a local file into a chat conversation.",
    "chat_download_file": "Download a file attached to a chat message.",
    # payments
    "payments_create_charge": "Create an uncaptured payment charge for a customer.",
    "payments_capture_charge": "Capture an authorized payment charge.",
    "payments_refund_charge": "Refund all or part of a captured payment charge.",
    "payments_void_charge": "Void an authorized charge before it is captured.",
    "payments_create_invoice": "Create an invoice with line items and a due date.",
    "payments_send_invoice": "Send an existing invoice to its billing recipient.",
    "payments_pay_invoice": "Pay an outstanding invoice with a stored method.",
    "payments_cancel_invoice": "Cancel an unpaid invoice and stop collection attempts.",
    "payments_add_method": "Attach a payment method to a customer account.",
    "payments_remove_method": "Detach a payment method from a customer account.",
    "payments_get_balance": "Return available and pending balances for an account.",
    "payments_transfer_funds": "Transfer a specified amount to another account.",
}

_SUBSET_15_NAMES = [
    "files_read_document",
    "files_search_content",
    "shell_run_command",
    "shell_capture_output",
    "web_search_pages",
    "web_fetch_page",
    "calendar_create_event",
    "calendar_find_events",
    "email_send_message",
    "email_reply_thread",
    "crm_create_contact",
    "deploy_rollback_release",
    "data_query_table",
    "chat_send_message",
    "payments_refund_charge",
]

_SUBSET_30_NAMES = _SUBSET_15_NAMES + [
    "files_copy_document",
    "shell_start_process",
    "web_extract_text",
    "calendar_get_availability",
    "email_search_messages",
    "crm_search_contacts",
    "deploy_promote_release",
    "data_describe_table",
    "chat_search_messages",
    "payments_create_charge",
    "files_get_metadata",
    "shell_list_processes",
    "web_check_status",
    "calendar_update_event",
    "email_archive_message",
]

_SUBSET_60_NAMES = _SUBSET_30_NAMES + [
    "files_write_document",
    "files_move_document",
    "files_find_path",
    "shell_stop_process",
    "shell_restart_process",
    "shell_stream_output",
    "web_fetch_file",
    "web_open_link",
    "web_extract_links",
    "calendar_cancel_event",
    "calendar_move_event",
    "calendar_book_slot",
    "email_draft_message",
    "email_forward_message",
    "email_find_thread",
    "crm_update_contact",
    "crm_merge_contacts",
    "crm_create_deal",
    "deploy_start_release",
    "deploy_pause_rollout",
    "deploy_scale_service",
    "data_insert_rows",
    "data_update_rows",
    "data_export_csv",
    "chat_edit_message",
    "chat_reply_thread",
    "chat_get_history",
    "payments_capture_charge",
    "payments_create_invoice",
    "payments_send_invoice",
]

_SUBSET_120_NAMES = [
    "files_read_document",
    "files_write_document",
    "files_append_document",
    "files_copy_document",
    "files_move_document",
    "files_delete_document",
    "files_list_directory",
    "files_search_content",
    "files_find_path",
    "files_compare_documents",
    "files_get_metadata",
    "files_set_permissions",
    "shell_run_command",
    "shell_start_process",
    "shell_stop_process",
    "shell_restart_process",
    "shell_stream_output",
    "shell_capture_output",
    "shell_set_environment",
    "shell_get_environment",
    "shell_list_processes",
    "shell_kill_process",
    "shell_run_script",
    "shell_check_exit",
    "web_search_pages",
    "web_fetch_page",
    "web_fetch_file",
    "web_open_link",
    "web_extract_text",
    "web_extract_links",
    "web_check_status",
    "web_monitor_status",
    "web_submit_form",
    "web_download_asset",
    "web_upload_asset",
    "web_validate_url",
    "calendar_create_event",
    "calendar_update_event",
    "calendar_cancel_event",
    "calendar_move_event",
    "calendar_list_events",
    "calendar_find_events",
    "calendar_get_availability",
    "calendar_book_slot",
    "calendar_add_attendee",
    "calendar_remove_attendee",
    "calendar_create_reminder",
    "calendar_snooze_reminder",
    "email_send_message",
    "email_draft_message",
    "email_reply_thread",
    "email_forward_message",
    "email_archive_message",
    "email_delete_message",
    "email_search_messages",
    "email_find_thread",
    "email_mark_read",
    "email_mark_unread",
    "email_add_label",
    "email_remove_label",
    "crm_create_contact",
    "crm_update_contact",
    "crm_merge_contacts",
    "crm_create_company",
    "crm_update_company",
    "crm_log_activity",
    "crm_add_note",
    "crm_search_contacts",
    "crm_find_deal",
    "crm_create_deal",
    "crm_update_deal",
    "crm_close_deal",
    "deploy_build_artifact",
    "deploy_start_release",
    "deploy_promote_release",
    "deploy_rollback_release",
    "deploy_pause_rollout",
    "deploy_resume_rollout",
    "deploy_scale_service",
    "deploy_restart_service",
    "deploy_view_logs",
    "deploy_check_health",
    "deploy_create_environment",
    "deploy_delete_environment",
    "data_query_table",
    "data_insert_rows",
    "data_update_rows",
    "data_delete_rows",
    "data_export_csv",
    "data_import_csv",
    "data_create_table",
    "data_drop_table",
    "data_describe_table",
    "data_count_rows",
    "data_validate_schema",
    "data_compare_snapshots",
    "chat_send_message",
    "chat_edit_message",
    "chat_delete_message",
    "chat_reply_thread",
    "chat_start_thread",
    "chat_close_thread",
    "chat_search_messages",
    "chat_get_history",
    "chat_add_reaction",
    "chat_remove_reaction",
    "chat_upload_file",
    "chat_download_file",
    "payments_create_charge",
    "payments_capture_charge",
    "payments_refund_charge",
    "payments_void_charge",
    "payments_create_invoice",
    "payments_send_invoice",
    "payments_pay_invoice",
    "payments_cancel_invoice",
    "payments_add_method",
    "payments_remove_method",
    "payments_get_balance",
    "payments_transfer_funds",
]


def _catalog_for(names: list[str]) -> dict[str, str]:
    return {name: CATALOG_120[name] for name in names}


SUBSETS: dict[int, dict[str, str]] = {
    15: _catalog_for(_SUBSET_15_NAMES),
    30: _catalog_for(_SUBSET_30_NAMES),
    60: _catalog_for(_SUBSET_60_NAMES),
    120: _catalog_for(_SUBSET_120_NAMES),
}
